### ISSUE TITLE
unable to stop kube apiserver operator: timed out waiting for the condition

### ISSUE THREAD

**Issue by dmage** [openshift/cluster-image-registry-operator#251]
```
panic: unable to stop kube apiserver operator: timed out waiting for the condition

goroutine 1 [running]:
github.com/openshift/cluster-image-registry-operator/test/e2e.TestMain(0xc420491b00)
	/go/src/github.com/openshift/cluster-image-registry-operator/test/e2e/main_test.go:29 +0x1f2
main.main()
	_testmain.go:74 +0x151
FAIL	github.com/openshift/cluster-image-registry-operator/test/e2e	301.449s
```
/kind test-flake

**Comment by dmage** [comment]
I haven't seen it for a while.
